(source melpa)

(depends-on "ag")
(depends-on "cask")
(depends-on "dash")
(depends-on "enh-ruby-mode")
(depends-on "epl")
(depends-on "f")
(depends-on "magit")
(depends-on "markdown-mode")
(depends-on "minitest")
(depends-on "monokai-theme")
(depends-on "pallet")
(depends-on "python-mode")
(depends-on "robe")
(depends-on "s")
(depends-on "web-mode")
(depends-on "yaml-mode")
